### PR TITLE
A lot of updates for the Angular scaffold

### PR DESCRIPTION
**Pull request by RussMax783**
Christian, I cant get the minification/compile to work. If you could look at that for me and see if you can spot anything im missing. 

I have made a lot of changes that i would like to approve with Cade and Christian. I have searched and searched through best practices guides and have come up with this solution. At first glance you may not like it.  I didn't. But as I used it in a different project on a bigger scale it was so much nicer then the way we have been doing things.  I really want your guys's feedback and opinions!

### CODE REVIEW

**Comment by cedub** [comment]
@RussMax783, what specific errors are you getting.  I've tried looking over your code and things seem to be in order but I'll dig in a bit more to see if I can determine what might be missing.

**Comment by cadebward** [comment]
@RussMax783, i pulled down the code and ran compile and it seems to have worked for me. 

EDIT: It didn't add the compiled css to the `index.html`

**Comment by RussMax783** [comment]
there was the problem that the scss wasn't compiling and compressing but that is fixed now.  The problem is now that It wont add that compiled main.css file to the index.html

@cedub If there is any other grunt commands that you think we need to add let me know and i can look into them. I know we should add functionality for end-to-end testing which i will do in the near future, but i think the compile is going to be more important.

**Comment by cedub** [comment]
Looks awesome!

**Pull request merged**
